###
# Copyright (c) 2023, 2024 ArSysOp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#     ArSysOp - initial API and implementation 
###

name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.4  
    - name: Setup Maven
      run: echo "MAVEN_OPTS='-Xmx2048m'" > ~/.mavenrc
    - name: Cache maven repo
      uses: actions/cache@v2
      env:
        cache-name: cache-maven-repo
      with:
        # maven files are stored in `~/.m2/repository` on Linux/macOS
        path: |
          ~/.m2/repository
          !~/.m2/repository/ru/arsysop/svn
          !~/.m2/repository/.cache/tycho
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.sha1') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build with Maven
      run: mvn clean verify --no-transfer-progress -U 
   
